version: "3.8"

services:
  api:
    image: registry:5000/sensevoice/asrpri:latest
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.cpu == 1 # 只在 CPU 节点上部署
      restart_policy:
        condition: any
        max_attempts: 10
        delay: 10s
      labels:
        caddy: "http://asrpri-api:80"
        caddy.reverse_proxy: "{{upstreams 8000}}"
    volumes:
      - cache:/root/.cache
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      start_period: 1m
      retries: 3
    environment:
      - TMP_DIR=/app/tmp
      - SENSEVOICE_DEVICE=cpu #cuda:0
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - UVICORN_LOG_LEVEL=info
      # 动态加载配置
      - UVICORN_WORKERS=1
      - MAX_CONCURRENT_REQUESTS=32
      - MODEL_IDLE_TIMEOUT=1800
      - ENABLE_AUTO_UNLOAD=true
    networks:
      - caddy

  app:
    image: registry:5000/sensevoice/asrpri:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ttd-nest
      restart_policy:
        condition: any
        max_attempts: 10
        delay: 10s
      labels:
        caddy: "http://asrsrt:80"
        caddy.reverse_proxy: "{{upstreams 8000}}"
    volumes:
      - cache:/root/.cache
    environment:
      - TMP_DIR=/app/tmp
      - SENSEVOICE_DEVICE=cpu #cuda:0
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - UVICORN_LOG_LEVEL=info
    command: ["python", "asrsrt.py"]
    networks:
      - caddy

networks:
  caddy:
    external: true

volumes:
  cache:
